services:
  rabbitmq1:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - rabbitmq1-data:/var/lib/rabbitmq/
      - rabbitmq1-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - rabbitmq

  rabbitmq2:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - rabbitmq2-data:/var/lib/rabbitmq/
      - rabbitmq2-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - rabbitmq

  rabbitmq3:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - rabbitmq3-data:/var/lib/rabbitmq/
      - rabbitmq3-logs:/var/log/rabbitmq
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - rabbitmq

  haproxy:
    image: haproxy:3.2.2
    volumes:
      - ./configs/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq

networks:
  rabbitmq:

volumes:
  rabbitmq1-data:
  rabbitmq1-logs:
  rabbitmq2-data:
  rabbitmq2-logs:
  rabbitmq3-data:
  rabbitmq3-logs: